import { Knex } from "knex";
import { ETableNames } from "../ETableNames";

const cidades = [
  "Abadia dos Dourados",
  "Abaeté",
  "Abre Campo",
  "Acaiaca",
  "Alterosa",
  "Alto Caparaó",
  "Alto Jequitibá",
  "Alto Rio Doce",
  "Alvarenga",
  "Alvinópolis",
  "Alvorada de Minas",
  "Amparo do Serra",
  "Andradas",
  "Andrelândia",
  "Angelândia",
  "Antônio Carlos",
  "Antônio Dias",
  "Antônio Prado de Minas",
  "Araçaí",
  "Aracitaba",
  "Araporã",
  "Arapuá",
  "Araújos",
  "Araxá",
  "Arceburgo",
  "Arcos",
  "Areado",
  "Argirita",
  "Aricanduva",
  "Arinos",
  "Astolfo Dutra",
  "Ataléia",
  "Augusto de Lima",
  "Baependi",
  "Baldim",
  "Berilo",
  "Berizal",
  "Bertópolis",
  "Betim",
  "Bias Fortes",
  "Bicas",
  "Biquinhas",
  "Boa Esperança",
  "Bocaina de Minas",
  "Bom Repouso",
  "Bom Sucesso",
  "Bonfim",
  "Bonfinópolis de Minas",
  "Bonito de Minas",
  "Borda da Mata",
  "Botelhos",
  "Botumirim",
  "Brás Pires",
  "Brasilândia de Minas",
  "Brasília de Minas",
  "Brasópolis",
  "Braúnas",
  "Brumadinho",
  "Bueno Brandão",
  "Buenópolis",
  "Bugre",
  "Buritis",
  "Buritizeiro",
  "Cabeceira Grande",
  "Cabo Verde",
  "Cachoeira da Prata",
  "Cachoeira de Minas",
  "Cachoeira de Pajeú",
  "Cachoeira Dourada",
  "Caetanópolis",
  "Caeté",
  "Caiana",
  "Cajuri",
  "Caldas",
  "Camacho",
  "Camanducaia",
  "Cambuí",
  "Cambuquira",
  "Campanário",
  "Campanha",
  "Campestre",
  "Campina Verde",
  "Campo Azul",
  "Campo Belo",
  "Campo do Meio",
  "Campo Florido",
  "Campos Altos",
  "Campos Gerais",
  "Cana Verde",
  "Carlos Chagas",
  "Carmésia",
  "Carmópolis de Minas",
  "Carneirinho",
  "Carrancas",
  "Carvalhópolis",
  "Chalé",
  "Chapada do Norte",
  "Chapada Gaúcha",
  "Chiador",
  "Cipotânea",
  "Claraval",
  "Ervália",
  "Esmeraldas",
  "Espera Feliz",
  "Espinosa",
  "Espírito Santo do Dourado",
  "Estiva",
  "Estrela Dalva",
  "Estrela do Indaiá",
  "Estrela do Sul",
  "Eugenópolis",
  "Ewbank da Câmara",
  "Extrema",
  "Fama",
  "Fervedouro",
  "Florestal",
  "Formiga",
  "Formoso",
  "Fronteira",
  "Heliodora",
  "Iapu",
  "Ibertioga",
  "Ibiá",
  "Ibiaí",
  "Ibiracatu",
  "Ibiraci",
  "Ipaba",
  "Ipanema",
  "Ipatinga",
  "Itaipé",
  "Itajubá",
  "Itamarandiba",
  "Itamarati de Minas",
  "Itambacuri",
  "Itambé do Mato Dentro",
  "Itatiaiuçu",
  "Itaú de Minas",
  "Itaúna",
  "Itaverava",
  "Itinga",
  "Itueta",
  "Ituiutaba",
  "Itumirim",
  "Iturama",
  "Itutinga",
  "Jaboticatubas",
  "Jacinto",
  "Jacuí",
  "Joanésia",
  "João Monlevade",
  "João Pinheiro",
  "Joaquim Felício",
  "Jordânia",
  "José Gonçalves de Minas",
  "José Raydan",
  "Josenópolis",
  "Juatuba",
  "Juiz de Fora",
  "Juramento",
  "Juruaia",
  "Lassance",
  "Lavras",
  "Leandro Ferreira",
  "Leme do Prado",
  "Leopoldina",
  "Liberdade",
  "Lima Duarte",
  "Limeira do Oeste",
  "Lontra",
  "Luisburgo",
  "Luislândia",
  "Luminárias",
  "Luz",
  "Machacalis",
  "Machado",
  "Madre de Deus de Minas",
  "Malacacheta",
  "Mamonas",
  "Manga",
  "Manhuaçu",
  "Manhumirim",
  "Mantena",
  "Mar de Espanha",
  "Maravilhas",
  "Maria da Fé",
  "Mariana",
  "Marilac",
  "Mário Campos",
  "Maripá de Minas",
  "Marliéria",
  "Marmelópolis",
  "Martinho Campos",
  "Martins Soares",
  "Matipó",
  "Mato Verde",
  "Matozinhos",
  "Matutina",
  "Medeiros",
  "Medina",
  "Mendes Pimentel",
  "Mercês",
  "Mesquita",
  "Minas Novas",
  "Minduri",
  "Mirabela",
  "Miradouro",
  "Miraí",
  "Miravânia",
  "Moeda",
  "Moema",
  "Monjolos",
  "Monsenhor Paulo",
  "Montes Claros",
  "Montezuma",
  "Morada Nova de Minas",
  "Morro da Garça",
  "Morro do Pilar",
  "Munhoz",
  "Muriaé",
  "Mutum",
  "Muzambinho",
  "Nacip Raydan",
  "Nanuque",
  "Naque",
  "Natalândia",
  "Natércia",
  "Nazareno",
  "Nepomuceno",
  "Ninheira",
  "Nova Belém",
  "Nova Era",
  "Nova Lima",
  "Nova Módica",
  "Nova Ponte",
  "Novo Oriente de Minas",
  "Novorizonte",
  "Olaria",
  "Olhos-d'Água",
  "Olímpio Noronha",
  "Oliveira",
  "Oliveira Fortes",
  "Onça de Pitangui",
  "Oratórios",
  "Orizânia",
  "Ouro Branco",
  "Ouro Fino",
  "Ouro Preto",
  "Ouro Verde de Minas",
  "Padre Carvalho",
  "Padre Paraíso",
  "Pai Pedro",
  "Paineiras",
  "Pains",
  "Paiva",
  "Palma",
  "Palmópolis",
  "Papagaios",
  "Pará de Minas",
  "Paracatu",
  "Patis",
  "Patos de Minas",
  "Patrocínio",
  "Patrocínio do Muriaé",
  "Paula Cândido",
  "Paulistas",
  "Pavão",
  "Peçanha",
  "Pedra Azul",
  "Pedra Bonita",
  "Pedra do Anta",
  "Pitangui",
  "Piumhi",
  "Santa Juliana",
  "Santa Luzia",
  "Santa Margarida",
  "Santa Vitória",
  "Santana do Garambéu",
  "São Domingos das Dores",
  "São Domingos do Prata",
  "São Félix de Minas",
  "Serra Azul de Minas",
  "Serra da Saudade",
  "Serra do Salitre",
  "Sete Lagoas",
  "Setubinha",
  "Silveirânia",
  "Silvianópolis",
  "Simão Pereira",
  "Virgolândia",
  "Visconde do Rio Branco",
  "Volta Grande",
  "Wenceslau Braz",
];

export const seed = async (knex: Knex) => {
  const [{ count }] = await knex(ETableNames.cidade).count<[{ count: number }]>(
    "* as count"
  );

  if (!Number.isInteger(count) || Number(count) > 0) return;

  const cidadesToInsert = cidades.map((cidade) => ({ nome: cidade }));
  console.log(cidadesToInsert);
  await knex(ETableNames.cidade).insert(cidadesToInsert);
};
